replicaCount: 1

image:
  repository: deckerego/docidx
  tag: latest
  pullPolicy: Always

jvm:
  ms: "512m"
  mx: "1g"

resources:
  requests:
    cpu: "2000m"
    memory: "2560Mi"

volumes:
  document:
    storage: 400Gi

nodeSelector: {}

tolerations: []

affinity: {}
