replicaCount: 1

image:
  repository: deckerego/docmagui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - docmag.local
  tls: []

environment:
  documentRoot: /usr/share/docmagui/docs

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"

nodeSelector: {}

tolerations: []

affinity: {}
